### ISSUE TITLE
Does the package work for other classifications?

### ISSUE THREAD

**Issue by raphael-gouvea** [ropensci/comtradr#16]
@ChrisMuir , does the package work with other classifications? I tried using SITCrev4 and it failed. I could not find an option on `ct_search` related to the database type.

```{r}
library(comtradr)
# Update and select SITCrev4
ct_update_databases(commodity_type = "SITCrev4")
#> Updates found. The following datasets have been downloaded: commodities DB
ct_commodity_db_type()
#> [1] "SITCrev4"
ex_1 <- ct_search(reporters = "China",
                  partners = c("Rep. of Korea", "USA", "Mexico"),
                  trade_direction = "exports")
#> Error: API request failed, with status code [200]
#> Fail Reason: SITCrev4 is an invalid trade classification
```

**Comment by ChrisMuir** [comment]
Hi Raphael,

Thank you for reporting this! Yes the intention is for the package to work with any of the commodity-type classifications that the UN Comtrade supports.....the error is being caused by a bug in how the pkg indicates commodity classification (it's passing the string `SITCrev4`, while the API is looking for `S4`).

I will try to get this fixed this weekend. Thanks again!

**Comment by ChrisMuir** [comment]
Just pushed a fix for this, @raphael-gouvea do you mind pulling the dev version of the pkg from GitHub and trying again?

**Comment by ChrisMuir** [comment]
Arg, that error was related to a bug in one of the calls to `sprintf()`. I just patched that bug, can you give it another shot?

What's alarming though is that the `sprintf()` error indicates your API request returned a status code that was NOT `200`.

**Comment by raphael-gouvea** [comment]
Thanks @ChrisMuir, it worked. Sorry for the delay.

**Comment by ChrisMuir** [comment]
Cool, no worries. Thanks again for bringing this to my attention!
