### ISSUE TITLE
Bulk/large download

### ISSUE THREAD

**Issue by zauster** [ropensci/comtradr#22]
Hey,
assuming I wanted to download the whole or a very large fraction of the UN Comtrade data using `comtradr`, how would i go about that?

I guess I would have to write nested loops of reporters and partners so that each single request is not that big, right? And include a longer waiting period once the request limit (for one hour?) has been reached?

I am asking because I am thinking how one could use the [etl](https://github.com/beanumber/etl) package to create a local SQL Comtrade DB. I have started coding [here](https://gitlab.com/zauster/comtradedb), but the downloading ("extracting") part is missing...

**Comment by pachamaltese** [comment]
Hi @zauster 
COMTRADE requires special access tokens for large downloads or it imposes restrictions on both query limits and number of queries per hour.
I know it's not exactly what you are asking for but github.com/ropensci/tradestatistics provides cleaned data obtained from comtrade. The main site for the project is tradestatistics.io
If you need raw data, please email me at mvargas@dcc.uchile.cl to see if I can help you. I have the raw data but according to an email from UN COMTRADE I cannot upload it or make it available from tradestatistics.io.

**Comment by zauster** [comment]
> UN COMTRADE requires special access tokens for large downloads or it imposes restrictions on both query limits and number of queries per hour.

Exactly, that's why I asked how to best deal with that issues.

> I know it's not exactly what you are asking for but github.com/ropensci/tradestatistics provides cleaned data obtained from comtrade. The main site for the project is tradestatistics.io

Your project -- actually all your projects -- look very interesting. I would, however, rather have the data as reported from the UN Comtrade.

> If you need raw data, please email me at [mvargas@dcc.uchile.cl](mailto:mvargas@dcc.uchile.cl) to see if I can help you. I have the raw data but according to an email from UN COMTRADE I cannot upload it or make it available from tradestatistics.io.

Actually I have the raw data, I am interesting in how to reproduce that dataset locally.

**Comment by jluisrg97** [comment]
Hi! I'm having some trouble because as @zauster said, a for loop is needed to download a large fraction of the UN Comtrade data. I just need information from certain countries but all commodity codes so I do the following 
test_hs2012 # list of HS codes
iteradores <- seq(1 , 2000 , by = 20)
for (i in iteradores) {             # Para cada elemento de test_hs2012, hacer:
  name <- paste("comtrade" , i , sep = "_")  # Un objeto (que será data frame) que se llame comtrade_i, donde i
  # es el número de iteración.
  assign(name , ct_search(reporters = "Denmark" ,
                          partners = "China" ,  # Assign se interpreta así:
                          trade_direction = "imports" ,       # assign(nombre del objeto a crear , valores del objeto)
                          freq = "annual" ,                   # Resultado: Un data frame por iteración.
                          commod_codes = test_hs2012[i:(i+19)] ,  # Extraer la serie del elemento i al i+19
                          start_date = "all" ,             
                          end_date = "all"))
  
  Sys.sleep(1) # Para "dormir" el sistema un segundo                                     
  
}

My problem is that sometimes it returns data frames with 0 obs. and when I run the code again, it returns the same query but with more obs. I'd like to know why that could be happening and how to fix it. Also, I would appreciate a lot if you could share with me the raw data. Thanks in advance.

**Comment by Hancky452** [comment]
Hi!  I've met similar question too. I tried to get datas without codes. There would return 0 obs occasionally.  I think this is uncomtrade website's problem. So just try more times. (LOLI will be grateful if you can tell me some wisely methods.  Thanks.

**Comment by ChrisMuir** [comment]
Hi @jluisrg97 ! Are you looking for the return data to be broken down by individual commodity? If not, then for the example query that you posted, there actually is no need to iterate through groups of commodities, you can skip the `commod_codes` arg all together, and the query will return results on all commodities.

```r
df <- ct_search(reporters = "Denmark" ,
                partners = "China" , # Assign se interpreta así:
                trade_direction = "imports" , # assign(nombre del objeto a crear , valores del objeto)
                freq = "annual" , # Resultado: Un data frame por iteración.
                #commod_codes = test_hs2012[i:(i+19)] , # Extraer la serie del elemento i al i+19
                start_date = "all" ,
                end_date = "all")

nrow(df)
```
```
#> 31
```

> My problem is that sometimes it returns data frames with 0 obs. and when I run the code again, it returns the same query but with more obs.

Yeah as Hancky452 mentioned, sometimes UN Comtrade's API will error out or time out, and sometimes will return zero data. Sometimes the API will send back a (somewhat) helpful error message, when that happens comtradr will throw an error that includes the API error message.

> I would appreciate a lot if you could share with me the raw data

I don't have access to the raw data. I've only built an R client that provides access to the UN's public API.

**Comment by jluisrg97** [comment]
Oh, thanks for your answer, @ChrisMuir . I need all the 6-digit level codes related to manufacturing. I also want to know if this series are consistent over time or if I need to do something else to do some modelling with them. I know th

**Comment by ChrisMuir** [comment]
Hey @jluisrg97 it looks like your last message got cut off at the end?

**Comment by elfatherbrown** [comment]
Ive been struggling like everyone (I guess) to get this data. I can share the following tips to help:

1. Make a local forward proxy cache so that you can cache your queries locally and be able to repeat without expending your precious API GET's. I used apache mod_proxy and can give you a quick apache conf if you msg me. The gist of it is:

ProxyPass /  https://comtrade.un.org/
ProxyPassReverse / https://comtrade.un.org/

The rest is embarrasing to post here because i only know it works for me and nothing else.

2. Use the url parameter to ct_search for this purpose. My cache listens on localhost:3333 so you point url there with url="http://localhost:33333/api/get?"

3. Chunk your stuff to the API requirements and use Sys.sleep. 

This will chunk any vector in chunks of 20:

`chunk_vector <- function(vtr, max.len = 20) {
  split(vtr, ceiling(seq_along(vtr) / max.len))
}`

This chunks dates by years in chunks of size 5. It needs work but, again, its enough for me:

Use lubridate and pass actual dates to it:

`chunk_dates <- function(start_date, end_date, size = 5) {
  force(start_date)
  force(end_date)
  interval(start_date, end_date) -> mainint
  as.period(mainint, unit = "years") -> mainper
  mainper@year -> yearspan
  chunk_vector(seq(from = start_date, to = end_date, by = 'year'), max.len = size) %>%
    rlist::list.apply(function(dates) {
      min(dates) -> mi
      max(dates) -> ma
      list(start = mi,
           end = ma + period(11, 'months') + period(31, 'days'))
    })
}`

Also a bit embarrassing, but this one here waits for an hour if you've exhausted your queries for the hour. Now bear in mind the counter is locally kept. Upstream Comtrade API does not tell you how many queries you have left.

`ct_wait_for_available <- function(at_least = 2) {
  ct_register_token(COMTRADE_TOKEN)

  repeat {
    ct_get_remaining_hourly_queries() -> remqueries
    message(
      paste0(
        "\n ",
        at_least,
        "<=",
        remqueries ,
        " queries remaining in COMTRADE API query for the hour",
        "\n Time to next cycle is:",
        ct_get_reset_time()
      )
    )
    if (remqueries <= at_least) {
      ct_get_reset_time() - lubridate::now() -> remtime
      cat(paste0(
        "\nStill ",
        remtime,
        " ",
        units(remtime),
        " to reset counter \n"
      ))
      wtime <-
        as.period(remtime) + period(1, units = "mins")
      if (as.numeric(wtime) > 0) {
        cat(paste0("\nSleeping ", as.numeric(wtime), " seconds"))
        Sys.sleep(as.numeric(wtime))
      } else {
        break
      }
    } else {
      break

    }
  }
}`

**Comment by datapumpernickel** [comment]
Closing, as we do not support bulk download at the moment and the API to do that has changed. 

However, it is on the list as a future feature!

**Comment by pachadotdev** [comment]
@zauster @datapumpernickel I have backups of UN COMTRADE bulk files
