### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by madsoeni** [ropensci/comtradr#26]
Hi all,

I am pretty new to an advanced use of R, so apologies if this is something very easy to fix. 
When trying to use the command I am immediately blocked by the following error message: 
"Error in curl:: curl_fetch_memory(url, handle=handle) : 
SSL peer certificate or SSH remote key was not OK. 

Do you have any suggestion on how to solve this? 

Best, 
Emanuele

**Comment by jcriveross** [comment]
Hi, same issue here.
But it seems related to the comtrade.org site. According to a SSL checker its certificate isa expired.
JC

The certificate has expired.
The certificate has expired. This server is not secure.
One of the root or intermediate certificates has expired (8 days ago).

**Comment by ChrisMuir** [comment]
Hey all, yep this is due to the SSL cert for the Comtrade website expiring. It was reported a few days ago [here](https://github.com/ropensci/comtradr/issues/25). It also came up in late May three years ago, in 2017 (see [here](https://github.com/ropensci/comtradr/issues/1)). For now, there's nothing that can be done to (safely) get around the issue. Here is my plan for now:
>When this came up 3 years ago, I sent CRAN a note asking them to archive the package, and contacted the Comtrade team via their "bug report" intake form a few times a week, asking them to consider upgrading their certs. They eventually did. I will start by sending them a few messages inquiring about it, if I don't hear back within a week, I will get in touch with CRAN.
