### ISSUE TITLE
New Maintainer Needed

### ISSUE THREAD

**Issue by ChrisMuir** [ropensci/comtradr#44]
Hello all, I am the author and current maintainer of the comtradr package. Recently the UN has introduced breaking changes to their data API, this package will need extensive updates to get it working again.

I have lost the appetite to continue maintaining this package. I am working with rOpenSci to try to find one or more individuals that would like to take ownership of the package, get it working again, and stay on top of maintenance. I'm happy to help with the transition and hand-off.

@maelle @ropensci/admin

**Comment by datapumpernickel** [comment]
Hi Chris! 

first of all, thanks for all your work on this. I have used this package quite frequently - i am sure it is/was of tremendous help to a lot of people!
I would be up for helping to maintain the comtradr package. As I have only little experience with building packages and the open source world, I am not sure whether I can do it alone though. 

In a bit of a rush decision, I have started an alternative [version](https://github.com/datapumpernickel/untrader), on the one hand, because I needed a wrapper for the API, but also because I had thought that maybe you were not active anymore. 

In part I also started the new package, because: 
1) there is quite some changes to the UN API that would require extensive changes to the comtradr package and it seemed easier to just start fresh, rather than troubleshoot my way through existing functions
2) there is new packages, such as httr2 that nicely implement wrapping APIs that I wanted to include

This leads me to the question (and I lack the experience in open source to properly answer this), whether it makes sense to maintain comtradr and implement all the necessary changes, or whether it makes more sense to archive this as is and to not run into the risk that people who knew the package wonder about some changes in the syntax, but to start "fresh" for a complete re-do of the wrapper (maybe copying over some of the functions that are still helpful with proper citation of course).

**Comment by maelle** [comment]
:wave: @ChrisMuir @datapumpernickel! The choice is up to you but here are a few comments.

## If this repo is where the changes happen 

I _guess_ this is the best way for users to find the package, but at the same time the README of an archived comtradr repo could point to untrader anyway (no way to add such a link from CRAN but I suppose users would also use a search engine). :thinking: 

- Regarding making big changes to an existing package, https://ropensci.org/blog/2019/04/30/qualtrics-relaunch/ comes to mind. You could also add lifecycle errors https://lifecycle.r-lib.org/articles/communicate.html (since the functionality is broken anyway, you couldn't go through "soft" deprecation messages first); but with a changed web API I suppose mostly only keeping the name (and list of "old" authors) makes sense.
- We haven't done re-reviews often but would be open too, see https://github.com/ropensci/mregions/pull/62#issuecomment-1064465447 by @noamross 

Note that if you @datapumpernickel want to adopt the package, but not as part of rOpenSci suite, that's fair too, and we'd transfer the repo to you if @ChrisMuir agrees too.

## If this repo is archived

Then there'd be a link to untrader from the README, and untrader could still be submitted to rOpenSci software peer-review if that's of interest to @datapumpernickel

## For reference

- guide for authors submitting packages https://devdevguide.netlify.app/softwarereview_author.html
- rOpenSci maintainer cheatsheet https://devdevguide.netlify.app/maintenance_cheatsheet.html
- The HTTP testing in R online book https://books.ropensci.org/http-testing/ (with a chapter on httptest2 that can be used with httr2 https://books.ropensci.org/http-testing/httptest2.html)

**Comment by datapumpernickel** [comment]
Hi @maelle,

thank you very much for your input and guidance. As far as I can see now, we should stick to this repo then, because we would keep the name and also keep the authors list. That makes sense to me. 

My only worry was the extensive change in functions. As far as I understand now, that would not be an issue though, because the functions as of now are "broken" anyways. As I said, I lack experience in the r-package world, so my question would be: would I then fully delete functions that are superseded, together with their respective .Rd files and documentations or should there be some kind of "archive" to look at the previous version (maybe we keep one git branch named 'legacy-API' or something like that?)? My intuition would say to delete it, because the functions will never work again, so it would only add confusion for future (and to a degree also past) users. But I would just want to be sure that is the way to go.

I would very much like to stay within the rOpenSci suite of packages and I think a re-review would be amazing! More importantly with larger changes. My next question would be on the timeline. I am not sure, how fast I can get this to be fully functional again, not to speak of fully complying with the guidelines, so I cannot really commit to any specific date as when to finish the package. 

I have never worked with httptest2, but it looks really cool, as I was already wondering how I can write a test without putting my API token in there! Will definitely try to incorporate that. 

Lastly, I still have some questions around some of the files in the git-repo, e.g. the different badges that I do not fully understand, but maybe we can do that in the hand-off @ChrisMuir. 

Thanks again for the interesting hints and information!

**Comment by hgoers** [comment]
Hey @datapumpernickel, @ChrisMuir and @maelle,

I would love to help out with this project, if you want an extra pair of hands. I really relied on ‘comtradr’ for my research: it’s a fantastic package. 

@datapumpernickel ‘untrader’ works brilliantly with the new API, so I would be happy to help build it out (as ‘comtradr’ or ‘untrader’) and document it. I have a lot of experience with package development. I have also gone through some of the pain of dealing with the transition to the new API so I am getting familiar with its quirks. 

Please let me know if I can help out in any way.

**Comment by ChrisMuir** [comment]
@hgoers Hey, thanks for volunteering! At this point it's up to @datapumpernickel , I'll let you all chat and figure out the distribution the work.

@datapumpernickel I'm happy to step aside on this existing repo and let you take control of it. I'd love it if my name stayed in the `DESCRIPTION ` file as an author, but in this scenario you'd 100% also add your name as an Author and the Maintainer.

```
Would I then fully delete functions that are superseded, together with their respective .Rd files and documentations or should there be some kind of "archive" to look at the previous version (maybe we keep one git branch named 'legacy-API' or something like that?)?
```
I don't think there's any reason to keep those old functions around (as they exist now), if they no longer work. I agree with 
@maelle ,  there may be some benefit in keeping the functions defined, but have them immediately return a msg to the user letting them know the func is deprecated, and explaining why (Comtrade API introduced breaking changes). Bump the comtradr version from `0.3.0` up to `1.0.0`, since there's so many breaking changes.

```
Lastly, I still have some questions around some of the files in the git-repo, e.g. the different badges that I do not fully understand, but maybe we can do that in the hand-off
```
I'm happy to answer any questions, please feel free to reach out to me via email if you'd like, my email is in the `DESCRIPTION`.

**Comment by maelle** [comment]
>  there may be some benefit in keeping the functions defined, but have them immediately return a msg to the user letting them know the func is deprecated, and explaining why (Comtrade API introduced breaking changes). 

Yes this way users would have a better way to find out how to update their code.

**Comment by maelle** [comment]
@hgoers thanks for volunteering! Hopefully you and @datapumpernickel can collaborate.

**Comment by maelle** [comment]
>  My next question would be on the timeline. I am not sure, how fast I can get this to be fully functional again, not to speak of fully complying with the guidelines, so I cannot really commit to any specific date as when to finish the package.

Absolutely no worries!

**Comment by datapumpernickel** [comment]
Hi @ChrisMuir and @maelle 
Thanks for the detailed answers. I think I understood how to deprecate the functions now. It goes without saying that you stay listed as author of the package (even if we would have moved over to untrader, I think it would have made sense). I probably will reach out to you via email in the coming days, when I got a chance to properly look at everything. Thanks!

Hi @hgoers 
thanks, that would be wonderful! Experienced hands is exactly what we need. :) As I had said above, I would be very happy about co-maintaining with more people, so we can share the work. 

Lastly, I will also open a new issue in the next days with a more or less detailed list of things that I think would need to be done and we can discuss priorities and distribution of work there.

**Comment by hgoers** [comment]
> @datapumpernickel @hgoers could you both give us your email addresses so @yabellini can invite you to rOpenSci slack workspace?

@yabellini - I’ve sent you a dm in the R Ladies global slack group. Thanks for this!

**Comment by amannj** [comment]
Hi all,
I've contributed to comtradr before and would also like to get involved. I might also be in a position to help with access rights.

Cheers

**Comment by maelle** [comment]
@ChrisMuir @hgoers where is the best place for @amannj to get involved? Is it #45?

**Comment by maelle** [comment]
Thank you @amannj for volunteering. :smile_cat:

**Comment by datapumpernickel** [comment]
Hi @amannj,
Thank you also from my side for volunteering! Sorry for the delay, I am currently not able to work on this until next weekend. 
We have refactored most of the functions on the branch `api-update`. What we planned to do, was write a vignette for it and push those first updates to main soon, so that we can get some user feedback, before running into a direction that might not make sense. Once it seems stable, we wanted to look at getting another rOpenSci review and eventually get it on CRAN. 

We have someone on the team who has access rights, but we are still focussing only on the 'free' version for now. Once that is up and running, we wanted to implement the paid version. 

What would be very helpful at the moment, is if you would try out the package on the branch `api-update` and see if it works as you would expect it to work. Does that make sense?

**Comment by amannj** [comment]
Hi @datapumpernickel 

Thanks a lot and no worries at all. I've been following this project for a while and made some tiny contributions in the past. I want to ensure that `comtradr` remains alive. 

I'll take a look at `api-update` over the next couple of days, and we can take it from there.

**Comment by maelle** [comment]
I think this should be closed as there's activity in this package. Thank you!

**Comment by datapumpernickel** [comment]
Yes, thank you!
