### ISSUE TITLE
Data= NULL

### ISSUE THREAD

**Issue by rasundsbak** [ropensci/comtradr#61]
Hi. I am making an online lesson for using Comtradr. I have data from before, but now intention is to facilitate use for future users of package. Today when using the get.comtrade, i had answer from Console Data=NULL

Question: The API key. Is this my password, or the username that i made for "my comtrade premium"?
Will it be the same key as indicated for the users of python in this snip:

i just tried with my password but no success

subscription_key = '<YOUR KEY>' # comtrade api subscription key (from comtradedeveloper.un.org)
directory = '<OUTPUT DIR>'  # output directory for downloaded files 

from url: https://github.com/uncomtrade/comtradeapicall/blob/main/tests/example%20calling%20functions%20-%20notebook.ipynb

Kindly keep me enlightened here. Please tell me if i can do anything for your project.
Best wishes from Rani in Oslo

**Comment by rasundsbak** [comment]
I found this recipe: https://unstats.un.org/wiki/display/comtrade/New+Comtrade+User+Guide under "un comtrade API management". Working on it :)

**Comment by datapumpernickel** [comment]
Hi Rani!

thanks for your question. We are happy about feedback for the package!

Just to clarify, you are using the latest version of comtradr, installed from this github repo, correct? 

Yes, I also found getting the new API key a bit of a hussle, but you are on the right track! In the wiki you linked, the relevant part is here: 

https://unstats.un.org/wiki/display/comtrade/New+Comtrade+User+Guide#NewComtradeUserGuide-ObtainingyoursubscriptionkeyforNewComtradeAPIs. 

Once you have your primary key, you can submit it as shown in the README of the repo here. 

If you still get weird errors or dont get anywhere, you can also share the code you are currently using. We found that the newest version of R, because it might enforce openssl3 on some systems might cause some errors we havent tracked down yet.

**Comment by datapumpernickel** [comment]
Hi Rani,

thanks for letting us know. That is actually very reassuring to hear. Since we have refactored a lot of the functions, I was worried it was broken. :D 

Would you mind letting me know, if there is anything that would have helped you in terms of documentation that we might be missing to help people with getting their primary API key?
